import * as vscode from "vscode";

const en = {
  configure: "Configure provider",
  settings: "Provider settings",
  protocol: "Protocol",
  baseUrl: "Base URL",
  model: "Model ID",
  apiKey: "API key",
  apiKeyHint: "Leave blank to keep the saved key.",
  toolCalling: "This model supports tool calling",
  save: "Save",
  test: "Test connection",
  cancel: "Cancel",
  ask: "Ask",
  agent: "Agent",
  placeholder: "Ask Evir about your code…",
  send: "Send",
  stop: "Stop",
  emptyTitle: "Work with your own model",
  emptyBody: "Ask about code, or use Agent in a trusted workspace.",
  exampleExplain: "Explain the active project structure",
  exampleTests: "Find likely gaps in the test coverage",
  noWorkspace: "Open a local workspace to use Agent.",
  untrustedWorkspace: "Trust this workspace to use Agent tools.",
  remoteWorkspace: "Agent tools currently require a local file workspace.",
  noTools: "Mark the configured model as tool-capable to use Agent.",
  agentDisclosure: "Agent may send relevant workspace content to your configured provider.",
  approval: "Approval required",
  approve: "Allow once",
  deny: "Deny",
  configured: "Provider configuration saved.",
  testing: "Testing provider connection…",
  testPassed: "Provider connection succeeded.",
  testFailed: "Provider connection failed",
  stopped: "Stopped.",
  missingProvider: "Configure a provider before sending a message.",
  invalidMessage: "The extension rejected an invalid UI message.",
  unexpectedError: "Evir encountered an unexpected error.",
};

const zh: typeof en = {
  configure: "配置模型服务",
  settings: "模型服务设置",
  protocol: "协议",
  baseUrl: "Base URL",
  model: "模型 ID",
  apiKey: "API Key",
  apiKeyHint: "留空将继续使用已保存的密钥。",
  toolCalling: "该模型支持工具调用",
  save: "保存",
  test: "测试连接",
  cancel: "取消",
  ask: "问答",
  agent: "Agent",
  placeholder: "向 Evir 询问代码问题…",
  send: "发送",
  stop: "停止",
  emptyTitle: "使用你自己的模型",
  emptyBody: "询问代码问题，或在受信任的工作区中使用 Agent。",
  exampleExplain: "解释当前项目结构",
  exampleTests: "查找测试覆盖中的潜在缺口",
  noWorkspace: "打开一个本地工作区后才能使用 Agent。",
  untrustedWorkspace: "信任此工作区后才能使用 Agent 工具。",
  remoteWorkspace: "Agent 工具目前仅支持本地文件工作区。",
  noTools: "请确认当前模型支持工具调用后再使用 Agent。",
  agentDisclosure: "Agent 可能会把相关工作区内容发送到你配置的模型服务。",
  approval: "需要审批",
  approve: "本次允许",
  deny: "拒绝",
  configured: "模型服务配置已保存。",
  testing: "正在测试模型连接…",
  testPassed: "模型连接成功。",
  testFailed: "模型连接失败",
  stopped: "已停止。",
  missingProvider: "发送消息前请先配置模型服务。",
  invalidMessage: "扩展拒绝了一条无效的界面消息。",
  unexpectedError: "Evir 遇到意外错误。",
};

export type Strings = typeof en;

export function strings(): Strings {
  return vscode.env.language.toLowerCase().startsWith("zh") ? zh : en;
}
