import type { ProviderPreset } from "./types";
import { PROVIDER_OFFICIAL_LINKS } from "./provider-links";

export const PROVIDER_PRESETS = [
  {
    id: "openai",
    officialLinks: PROVIDER_OFFICIAL_LINKS["openai"],
    name: "OpenAI",
    region: "international",
    protocols: ["openai-responses", "openai-chat-completions"],
    recommendedProtocol: "openai-responses",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "global",
        label: "Global",
        baseUrl: "https://api.openai.com/v1",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "protocol-verified" as const,
  },
  {
    id: "anthropic",
    officialLinks: PROVIDER_OFFICIAL_LINKS["anthropic"],
    name: "Anthropic",
    region: "international",
    protocols: ["anthropic-messages"],
    recommendedProtocol: "anthropic-messages",
    authModes: ["x-api-key"],
    endpoints: [
      {
        id: "global",
        label: "Global",
        baseUrl: "https://api.anthropic.com",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "protocol-verified" as const,
  },
  {
    id: "google-gemini",
    officialLinks: PROVIDER_OFFICIAL_LINKS["google-gemini"],
    name: "Google Gemini API",
    region: "international",
    protocols: ["gemini-interactions", "gemini-generate-content"],
    recommendedProtocol: "gemini-interactions",
    authModes: ["query-api-key"],
    endpoints: [
      {
        id: "global",
        label: "Global",
        baseUrl: "https://generativelanguage.googleapis.com",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "protocol-verified" as const,
  },
  {
    id: "azure-openai",
    officialLinks: PROVIDER_OFFICIAL_LINKS["azure-openai"],
    name: "Microsoft Azure OpenAI",
    region: "international",
    protocols: ["azure-openai-responses", "azure-openai-chat"],
    recommendedProtocol: "azure-openai-responses",
    authModes: ["api-key-header", "azure-entra"],
    endpoints: [],
    supportsModelListing: false,
    webDirectCandidate: false,
    agentTier: "protocol-verified" as const,
    notes: ["Requires an Azure resource endpoint and deployment/model configuration."],
  },
  {
    id: "aws-bedrock",
    officialLinks: PROVIDER_OFFICIAL_LINKS["aws-bedrock"],
    name: "Amazon Bedrock",
    region: "international",
    protocols: ["aws-bedrock-converse"],
    recommendedProtocol: "aws-bedrock-converse",
    authModes: ["aws-sigv4"],
    endpoints: [],
    supportsModelListing: true,
    webDirectCandidate: false,
    agentTier: "preset" as const,
  },
  {
    id: "xai",
    officialLinks: PROVIDER_OFFICIAL_LINKS["xai"],
    name: "xAI",
    region: "international",
    protocols: ["openai-responses", "openai-compatible-chat"],
    recommendedProtocol: "openai-responses",
    authModes: ["bearer-api-key"],
    endpoints: [
      { id: "global", label: "Global", baseUrl: "https://api.x.ai/v1", site: "international" },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "openrouter",
    officialLinks: PROVIDER_OFFICIAL_LINKS["openrouter"],
    name: "OpenRouter",
    region: "international",
    protocols: ["openai-compatible-responses", "openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "global",
        label: "Global",
        baseUrl: "https://openrouter.ai/api/v1",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "groq",
    officialLinks: PROVIDER_OFFICIAL_LINKS["groq"],
    name: "Groq",
    region: "international",
    protocols: ["openai-compatible-chat", "openai-compatible-responses"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "global",
        label: "Global",
        baseUrl: "https://api.groq.com/openai/v1",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "together",
    officialLinks: PROVIDER_OFFICIAL_LINKS["together"],
    name: "Together AI",
    region: "international",
    protocols: ["openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "global",
        label: "Global",
        baseUrl: "https://api.together.xyz/v1",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "mistral",
    officialLinks: PROVIDER_OFFICIAL_LINKS["mistral"],
    name: "Mistral AI",
    region: "international",
    protocols: ["mistral-native", "openai-compatible-chat"],
    recommendedProtocol: "mistral-native",
    authModes: ["bearer-api-key"],
    endpoints: [
      { id: "eu", label: "EU", baseUrl: "https://api.mistral.ai/v1", site: "international" },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "google-vertex-ai",
    officialLinks: PROVIDER_OFFICIAL_LINKS["google-vertex-ai"],
    name: "Google Vertex AI",
    region: "international",
    protocols: ["vertex-gemini"],
    recommendedProtocol: "vertex-gemini",
    authModes: ["google-adc", "oauth-bearer"],
    endpoints: [],
    supportsModelListing: true,
    webDirectCandidate: false,
    agentTier: "preset" as const,
    notes: ["Requires project, location, and enterprise Google authentication."],
  },
  {
    id: "cohere",
    officialLinks: PROVIDER_OFFICIAL_LINKS["cohere"],
    name: "Cohere",
    region: "international",
    protocols: ["cohere-chat-v2"],
    recommendedProtocol: "cohere-chat-v2",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "global",
        label: "Global",
        baseUrl: "https://api.cohere.com/v2",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "fireworks",
    officialLinks: PROVIDER_OFFICIAL_LINKS["fireworks"],
    name: "Fireworks AI",
    region: "international",
    protocols: ["openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "global",
        label: "Global",
        baseUrl: "https://api.fireworks.ai/inference/v1",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "nvidia-nim",
    officialLinks: PROVIDER_OFFICIAL_LINKS["nvidia-nim"],
    name: "NVIDIA NIM",
    region: "international",
    protocols: ["openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "hosted",
        label: "Hosted",
        baseUrl: "https://integrate.api.nvidia.com/v1",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "perplexity",
    officialLinks: PROVIDER_OFFICIAL_LINKS["perplexity"],
    name: "Perplexity",
    region: "international",
    protocols: ["openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "global",
        label: "Global",
        baseUrl: "https://api.perplexity.ai",
        site: "international",
      },
    ],
    supportsModelListing: false,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "hugging-face",
    officialLinks: PROVIDER_OFFICIAL_LINKS["hugging-face"],
    name: "Hugging Face Inference Providers",
    region: "international",
    protocols: ["openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "router",
        label: "Inference Router",
        baseUrl: "https://router.huggingface.co/v1",
        site: "international",
      },
    ],
    supportsModelListing: false,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "deepseek",
    officialLinks: PROVIDER_OFFICIAL_LINKS["deepseek"],
    name: "DeepSeek",
    region: "china",
    protocols: ["openai-compatible-chat", "anthropic-compatible-messages"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      { id: "mainland", label: "中国大陆", baseUrl: "https://api.deepseek.com", site: "mainland" },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
    notes: ["Some tool-call turns require preserving provider-specific reasoning state."],
  },
  {
    id: "alibaba-model-studio",
    officialLinks: PROVIDER_OFFICIAL_LINKS["alibaba-model-studio"],
    name: "阿里云百炼 / 通义千问",
    region: "china",
    protocols: ["openai-compatible-responses", "openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-responses",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "beijing",
        label: "中国大陆（北京）",
        baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
        site: "mainland",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
    notes: ["Endpoints can differ by region."],
  },
  {
    id: "volcengine-ark",
    officialLinks: PROVIDER_OFFICIAL_LINKS["volcengine-ark"],
    name: "火山引擎方舟 / 豆包",
    region: "china",
    protocols: [
      "openai-compatible-responses",
      "openai-compatible-chat",
      "anthropic-compatible-messages",
    ],
    recommendedProtocol: "openai-compatible-responses",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "beijing",
        label: "中国大陆（北京）",
        baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
        site: "mainland",
      },
    ],
    supportsModelListing: false,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "tencent-hunyuan",
    officialLinks: PROVIDER_OFFICIAL_LINKS["tencent-hunyuan"],
    name: "腾讯混元 / TokenHub",
    region: "china",
    protocols: ["openai-compatible-chat", "anthropic-compatible-messages"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "hunyuan",
        label: "混元",
        baseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
        site: "mainland",
      },
      {
        id: "tokenhub",
        label: "TokenHub",
        baseUrl: "https://tokenhub.tencentmaas.com/v1",
        site: "mainland",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "baidu-qianfan",
    officialLinks: PROVIDER_OFFICIAL_LINKS["baidu-qianfan"],
    name: "百度智能云千帆",
    region: "china",
    protocols: ["openai-compatible-responses", "openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-responses",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "mainland",
        label: "中国大陆",
        baseUrl: "https://qianfan.baidubce.com/v2",
        site: "mainland",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "zhipu",
    officialLinks: PROVIDER_OFFICIAL_LINKS["zhipu"],
    name: "智谱 BigModel / GLM",
    region: "china",
    protocols: ["openai-compatible-chat", "anthropic-compatible-messages"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "mainland",
        label: "中国大陆",
        baseUrl: "https://open.bigmodel.cn/api/paas/v4",
        site: "mainland",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "agent-verified" as const,
  },
  {
    id: "moonshot-kimi",
    officialLinks: PROVIDER_OFFICIAL_LINKS["moonshot-kimi"],
    name: "Moonshot / Kimi",
    region: "china",
    protocols: ["openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      { id: "mainland", label: "中国站", baseUrl: "https://api.moonshot.cn/v1", site: "mainland" },
      {
        id: "international",
        label: "International",
        baseUrl: "https://api.moonshot.ai/v1",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "minimax",
    officialLinks: PROVIDER_OFFICIAL_LINKS["minimax"],
    name: "MiniMax",
    region: "china",
    protocols: ["anthropic-compatible-messages", "openai-compatible-chat"],
    recommendedProtocol: "anthropic-compatible-messages",
    authModes: ["bearer-api-key", "x-api-key"],
    endpoints: [
      {
        id: "mainland-openai",
        label: "中国站 · OpenAI",
        baseUrl: "https://api.minimaxi.com/v1",
        site: "mainland",
      },
      {
        id: "global-openai",
        label: "Global · OpenAI",
        baseUrl: "https://api.minimax.io/v1",
        site: "international",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "siliconflow",
    officialLinks: PROVIDER_OFFICIAL_LINKS["siliconflow"],
    name: "SiliconFlow 硅基流动",
    region: "china",
    protocols: ["openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "mainland",
        label: "中国大陆",
        baseUrl: "https://api.siliconflow.cn/v1",
        site: "mainland",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "stepfun",
    officialLinks: PROVIDER_OFFICIAL_LINKS["stepfun"],
    name: "阶跃星辰 StepFun",
    region: "china",
    protocols: ["openai-compatible-chat", "anthropic-compatible-messages"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "mainland",
        label: "中国大陆",
        baseUrl: "https://api.stepfun.com/v1",
        site: "mainland",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "iflytek-spark",
    officialLinks: PROVIDER_OFFICIAL_LINKS["iflytek-spark"],
    name: "讯飞星火",
    region: "china",
    protocols: ["openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "mainland",
        label: "中国大陆",
        baseUrl: "https://spark-api-open.xf-yun.com/v1",
        site: "mainland",
      },
    ],
    supportsModelListing: false,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "yi",
    officialLinks: PROVIDER_OFFICIAL_LINKS["yi"],
    name: "零一万物 Yi",
    region: "china",
    protocols: ["openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key"],
    endpoints: [
      {
        id: "mainland",
        label: "中国大陆",
        baseUrl: "https://api.lingyiwanwu.com/v1",
        site: "mainland",
      },
    ],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "ollama",
    officialLinks: PROVIDER_OFFICIAL_LINKS["ollama"],
    name: "Ollama",
    region: "local",
    protocols: [
      "ollama-native",
      "openai-compatible-responses",
      "openai-compatible-chat",
      "anthropic-compatible-messages",
    ],
    recommendedProtocol: "ollama-native",
    authModes: ["none-local"],
    endpoints: [{ id: "local", label: "Local", baseUrl: "http://127.0.0.1:11434", site: "local" }],
    supportsModelListing: true,
    webDirectCandidate: false,
    agentTier: "protocol-verified" as const,
  },
  {
    id: "lm-studio",
    officialLinks: PROVIDER_OFFICIAL_LINKS["lm-studio"],
    name: "LM Studio",
    region: "local",
    protocols: [
      "openai-compatible-responses",
      "openai-compatible-chat",
      "anthropic-compatible-messages",
    ],
    recommendedProtocol: "openai-compatible-responses",
    authModes: ["none-local"],
    endpoints: [
      { id: "local", label: "Local", baseUrl: "http://127.0.0.1:1234/v1", site: "local" },
    ],
    supportsModelListing: true,
    webDirectCandidate: false,
    agentTier: "preset" as const,
  },
  {
    id: "vllm",
    officialLinks: PROVIDER_OFFICIAL_LINKS["vllm"],
    name: "vLLM",
    region: "local",
    protocols: ["openai-compatible-responses", "openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["none-local", "bearer-api-key"],
    endpoints: [
      { id: "local", label: "Local", baseUrl: "http://127.0.0.1:8000/v1", site: "local" },
    ],
    supportsModelListing: true,
    webDirectCandidate: false,
    agentTier: "preset" as const,
  },
  {
    id: "llama-cpp",
    officialLinks: PROVIDER_OFFICIAL_LINKS["llama-cpp"],
    name: "llama.cpp server",
    region: "local",
    protocols: ["openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["none-local", "bearer-api-key"],
    endpoints: [
      { id: "local", label: "Local", baseUrl: "http://127.0.0.1:8080/v1", site: "local" },
    ],
    supportsModelListing: false,
    webDirectCandidate: false,
    agentTier: "preset" as const,
  },
  {
    id: "localai",
    officialLinks: PROVIDER_OFFICIAL_LINKS["localai"],
    name: "LocalAI",
    region: "local",
    protocols: ["openai-compatible-chat", "openai-compatible-responses"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["none-local", "bearer-api-key"],
    endpoints: [
      { id: "local", label: "Local", baseUrl: "http://127.0.0.1:8080/v1", site: "local" },
    ],
    supportsModelListing: true,
    webDirectCandidate: false,
    agentTier: "preset" as const,
  },
  {
    id: "litellm",
    officialLinks: PROVIDER_OFFICIAL_LINKS["litellm"],
    name: "LiteLLM Proxy",
    region: "local",
    protocols: [
      "openai-compatible-responses",
      "openai-compatible-chat",
      "anthropic-compatible-messages",
    ],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key", "none-local"],
    endpoints: [],
    supportsModelListing: true,
    webDirectCandidate: false,
    agentTier: "preset" as const,
  },
  {
    id: "custom-openai",
    name: "Custom OpenAI-compatible",
    region: "custom",
    protocols: ["openai-compatible-responses", "openai-compatible-chat"],
    recommendedProtocol: "openai-compatible-chat",
    authModes: ["bearer-api-key", "none-local"],
    endpoints: [],
    supportsModelListing: true,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
  {
    id: "custom-anthropic",
    name: "Custom Anthropic-compatible",
    region: "custom",
    protocols: ["anthropic-compatible-messages"],
    recommendedProtocol: "anthropic-compatible-messages",
    authModes: ["x-api-key", "bearer-api-key", "none-local"],
    endpoints: [],
    supportsModelListing: false,
    webDirectCandidate: true,
    agentTier: "preset" as const,
  },
] as const satisfies readonly ProviderPreset[];
